version: "3.9"

services:
  ibm-mq:
    build: ./ibm-mq
    image: ibm-mq
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - LICENSE=accept
      - MQ_DEV=false
      - MQ_QMGR_NAME=QMGRDEMO
      - MQ_ADMIN_PASSWORD=${MQ_ADMIN_PASSWORD}
    ports:
      - 1414:1414
      - 9443:9443
    volumes:
      - ibm-mq:/var/mqm
    networks:
      - ibm-mq

networks:
  ibm-mq:

volumes:
  ibm-mq:
