services:
  ibm-mq:
    build: ./ibm-mq
    image: ibm-mq
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - .env
    ports:
      - 1414:1414
      - 9443:9443
    volumes:
      - ibm-mq:/var/mqm
    networks:
      - ibm-mq

networks:
  ibm-mq:

volumes:
  ibm-mq:
